
language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t igorgurovich/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true igorgurovich/docker-react npm run test

